# Generated by Django 3.2 on 2021-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarista',
            name='cidade',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
